- hosts: servidores
  become: true
  tasks:

    - name: "Crear usuario"
      user:
          name: "ejercicio"
          state: present
          uid: "1222"
          password: "$6$sO85C2hJUeC4buY5$Qtd8/T.aTWE7bXwbxMPILIUWtnqXbxgn2QCizoP6i6PLqzNH52bp1s44fd0uchp2DAP7GsnJY0pE2tFeOGP4n1"
          shell: "/bin/bash"

    - name: "Descargar url"
      become: yes
      get_url:
             url: https://wordpress.org/latest.zip
             dest: /home/ejercicio


    - name: "Instalar paquete zip"
      apt:
        name: zip

    - name: "Descomprimir zip"
      unarchive:
       src: /home/ejercicio/wordpress-5.8.1.zip
       dest: /home/ejercicio
       remote_src: yes

    - name: "instalar mariadb"
      apt:
        name: mariadb-server

    - name: "instalar paquete python3-mysqldb"
      apt: 
        name: python3-mysqldb

    - name: "creación base de datos jesusrubio_wordpress"
      mysql_db: 
          name=jesusrubio_wordpress
          state=present


    - name: "crear usuario con permisos en la base de datos"
      mysql_user: 
         name=jesus_rubio
         host=localhost
         password=asdasd
         priv=jesusrubio_wordpress.*:ALL,GRANT
      with_items:
        - localhost

    - name: "Instalar paquete git"
      apt:
        name: git

    - name: "clonar repositorio"
      git:
        repo: https://github.com/josedom24/ansible_ejemplos.git
        dest: /home/ejercicio/github

